### PR TITLE
Feat: Added the avatar component's CSS and documentation page.

### PR DESCRIPTION
**Pull request by coldpigli**
Added new feature: Avatars

1) Default Avatars
default-rounded-avatar

2) Avatars - various dimensions
avatars-diff-sizes

3) Avatars - squircle
squircle-avatars

### CODE REVIEW

**Review by krishanu2911 — COMMENTED** [review]
A suggestion like in all the classes border-radius, vertical-align were repeating so you can specify it in a common class or else if you are not using common class then it's fine

**Review by kjais1720 — CHANGES_REQUESTED** [review]
Looks abstract and clean, just one suggestion, since vertical align and border-radius is needed in all the avatars, create a base class called `avatar` and give these properties to that class. So in the HTML, user can write `class = 'avatar avatar-sm` like this. You can do the same for any other component as well.

**Comment by coldpigli** [comment]
> A suggestion like in all the classes border-radius, vertical-align were repeating so you can specify it in a common class or else if you are not using common class then it's fine

Worked on the suggestion. I have extracted the common styles to the a common "avatar" class. Thanks

**Comment by coldpigli** [comment]
> Looks abstract and clean, just one suggestion, since vertical align and border-radius is needed in all the avatars, create a base class called `avatar` and give these properties to that class. So in the HTML, user can write `class = 'avatar avatar-sm` like this. You can do the same for any other component as well.

Worked on the suggestion. I have extracted the common styles to the a common "avatar" class. Thanks for the heads up : )

**Pull request merged**
